//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassScheduleAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int ID { get; set; }
        public Nullable<int> PublicCourseTypeID { get; set; }
        public Nullable<int> PublicCourseInfoID { get; set; }
        public string OpenID { get; set; }
        public Nullable<int> ChildrenID { get; set; }
        public string CourseName { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Address { get; set; }
        public string Teacher { get; set; }
        public string Phone { get; set; }
        public string RemindTime { get; set; }
        public string Remarks { get; set; }
        public string SchoolName { get; set; }
        public string CourseType { get; set; }
        public string Frequency { get; set; }
        public Nullable<System.Guid> BatchID { get; set; }
    }
}
